FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive 

ADD ci/deb/build.sh /opt/bin/
ADD ci/deb/build-dep.sh /opt/bin/
ADD ci/deb/makefile /opt/archive/

RUN echo /opt/bin/build-dep.sh

RUN apt-get update && \
    apt-get install -y \
    curl \
    git \ 
    cmake \
    build-essential \
    libssl-dev \
    wget \
    python3

RUN ln -s /opt/bin/build.sh /usr/local/bin/build \
&& /opt/bin/build-dep.sh

WORKDIR /opt/

CMD ["/usr/local/bin/build", "-h"]
